[package]
name = "harvester_app"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
harvester_core = { path = "../harvester_core" }
harvester_engine = { path = "../harvester_engine" }
commanductui = { path = "../../src/CommanDuctUI" }
log = "0.4"
env_logger = "0.11"
